### ISSUE TITLE
Feature Request:   provide a docker.file to use the patcher as container 

### ISSUE THREAD

**Issue by rICTx-T1D** [DiaKEM/dexcom-g7-apk-patcher#21]
Hi developers, 

have many thanks for your hard work on this great project!
Is it possible to publish a docker.file to create a container with anything you need to patch a apk-file?

Greetings 
rICTx

**Comment by khskekec** [comment]
Hey,

You are welcome. Actually the requirements are very low. Only Java 8+ and git is required. The rest is already integrated into the repo.

But yes, it could make things nevertheless easier for DEVS but not for non techies.

Would you like to shift the patching procedure to docker env. Did you had some difficulties on your own machine why this requirement came up?

Best regards

Selçuk

**Comment by rICTx-T1D** [comment]
Hi,
yes I would like to shift the patching process to docker environment.  So I don't need to have panic when other software need updates for java.

Non tech people have easy, because consumers storage systems (NAS) for example Synology or QNAP can host docker images with simple GUI administration. 

Otherwise I would install a separated virtual machine with a regular software installation.

**Comment by khskekec** [comment]
Hey,

Might be senseful because I get a feedback that the patcher does not work on windows systems.

Are you experienced in setting up docker. If so you are welcome to create a pr. Otherwise I will take it over.

Kind regards

Selçuk

**Comment by rICTx-T1D** [comment]
I make some experiments with dockerfile at the moment... so I think I can provide a first version as soon as possible.

**Comment by rICTx-T1D** [comment]
Please accept the pull request and we can close this issue

**Comment by khskekec** [comment]
Hey,

This looks great. I will checkout the general functionality and merge it if everything is okay.

And.... It so wonderful that your took this over. I really appreciate that you made this working and can support non techies maybe more then before.

Kind regards

Selçuk

**Comment by rICTx-T1D** [comment]
Iam happy that a solution for g7 and aaps is reachable.  So I will change over from g6 to g7 next quarter after approval from healthcare.

Additional: The link to discord is invalid and need a renewal.

**Comment by khskekec** [comment]
Hi @rICTx-T1D,

the link was renewed with a non expiring version now. It was not clear to me that Discord handles invitation links like that :(.

Here is the working link: https://discord.gg/MCCa2Xtaed

**Comment by khskekec** [comment]
And...

Thank you for your PR it inspired me a lot. I made some small changes and created a more integrated solution:

* The Dockerfile does not write the entry script file - it is part of the repo already
* A script for Linux/Unix hosts was created to automatically build the image and also start the container with correctly mounted volume

Would be great if you can check it and give me some feedback.

**Comment by khskekec** [comment]
Hey @rICTx-T1D,

do we still need this PR or are you satisfied with the current docker integration?
