### ISSUE TITLE
agreeing to disclaimer not working

### ISSUE THREAD

**Issue by 1spammer** [DiaKEM/dexcom-g7-apk-patcher#28]
Hi has anyone found out how to solve this issue? After my first login it asks me to Agree to the disclaimer but an "Connection error" pops up. If I hit OK the app closes, if i hit retry it keeps popping up.
![Screenshot_2023-01-12-23-01-29-501-edit_com dexcom g7](https://user-images.githubusercontent.com/71672185/212191249-61097c42-5b76-47eb-bb0a-85f4921069a1.jpg)

**Comment by khskekec** [comment]
Hi,

This is the first time I see this error.

It looks like you have VPN enabled. Can you try to disable it and try again?

You can also ask this question on discord. Might be that there is someone who faced this problem before.

**Comment by 1spammer** [comment]
I have already tried that, only cellular, VPN on/off,  Reboot, reinstalling tried different patches without any luck.
Without an existing internet Connection the Page doesn't even load and the popup still appears.
The only workaround I found was spanking on the retry button and try to hit the Disclaimer link. 
Than I had a little more Time before the popup was reappearing (about 2sec) but enough time to click those checkboxes and agree.

I think it has to do with the new account creation. Never used Dexcom before.

Android 12 MIUI 13.0.9
Xiaomi Mi 10T Pro 5G
Dexcom G7 App Version 1.3.3.3527

**Comment by khskekec** [comment]
Sry for my late response.

Unfortunately I do not have an answer whicj could explain why this is happening.

I tried it just know and i am able to login without any issues. 

Could you try to install the patched app on a compatible device and login with the stock and patched app. By doing this we can delimit the reason bit more. 

Kind regards 

Selçuk Kekeç

**Comment by khskekec** [comment]
Hey,

Any updates regarding this issue?

**Comment by 1spammer** [comment]
Sorry, I'm not in my Office at the moment. I don't have a compatible device, But I will try it in an emulated Android Environment Tomorrow.

As I said earlier the way I Accessed got it to work was:
Spanking on the retry button and try to hit the Disclaimer link.
Than I had a little more Time before the popup was reappearing (about 2sec) but enough time to click those checkboxes and agree.

Is there any way to debug that, so I could do any Help? 
![2](https://user-images.githubusercontent.com/71672185/212707118-7b609864-9c2f-4367-8218-8bb5e15c75a4.jpg)

**Comment by khskekec** [comment]
Hey,

Could you write an email to khskekec@gmail.com please?

**Comment by Arakon** [comment]
I just had the same issue. I have a VPN-based, local DNS ad blocker running (DNS66) and that seems to be blocking the access. Once I disabled it, the connection instantly worked fine. So if you run an ad blocker, add the G7 app as an exception.

**Comment by khskekec** [comment]
Hey @Arakon,

Thank you for you feedback. I will add this definetly to the Readme. I thunk this is the solution here. Read similar stuff in BYODA thread on reddit. 

Let us wait for feedback from the issuer and close it later.

Kind regards

Selçuk

**Comment by khskekec** [comment]
Closing the issue for now because no feedback from issuer was provided!
