### ISSUE TITLE
Exclude Location/GPS permissions to reduce battery consumption

### ISSUE THREAD

**Issue by khskekec** [DiaKEM/dexcom-g7-apk-patcher#32]
Hi,

@blaqone already tested the exclusion of GPS-Permissions to decrease the battery consumption of the G7 App.

Actually we know that receiving sensor readings without this permission works as expected.

The only case we have to test is to check if sensor activation/deactivation/calibration is also possible.

**Comment by blaqone** [comment]
Installing the app with disabled phone-wide GPS permissions does **not** work. 
I had to enable it, but was able to disable it after the gps location prompt

**Comment by blaqone** [comment]
Activating and connecting to a sensor only works with enabled GPS permissions.

**Comment by blaqone** [comment]
Calibrations do work with disabled GPS permissions.

**Comment by khskekec** [comment]
In this case best would be to grant the permission but extract the code which makes unnecessary calls to retrieve location informations. This would decrease the battery consumption a lot.

**Comment by blaqone** [comment]
I am unsure if this is an Android wide problem or feature: 
When i disable phone wide gps location, the g7 app works perfectly fine.
But when I remove the location permission only for the G7 app, the app does not get bg values.

**Comment by khskekec** [comment]
Hi,

@blaqone checked this again and the battery usage without location service is nearly zero.

That's why we will investigate this topic further..

Kind regards

Selçuk

**Comment by khskekec** [comment]
Hi @blaqone,

might be that this issue is resolved with new version right?

How should we deal with this issue ticket?

**Comment by blaqone** [comment]
@khskekec I think we can close it, as more people will use the latest version - and we know it completely different there.
