### ISSUE TITLE
Build end with failure.

### ISSUE THREAD

**Issue by osodebailar** [DiaKEM/dexcom-g7-apk-patcher#38]
After updating to new version with G7_1.4.0.3906 building ends with failure. See screen in atachment
![Screenshot from 2023-03-06 08-38-41](https://user-images.githubusercontent.com/25795894/223047702-77a01500-58eb-47b0-9a53-96b1cbfdf764.png)

**Comment by osodebailar** [comment]
> 

Hi @khskekec , The version before ( Dexcom G7_1.3.3.3527 ) works perfect. I am using an ubuntu linx Version 22.04.02 LTS. And no other errors occure while building. The dexcom apk  a am using is  Dexcom G7_1.4.0.3906_Apkpure

**Comment by khskekec** [comment]
Hey,

really interesting case. Can you try to use docker first before we dive deeper into this issue.

Kind regards

Selçuk

**Comment by osodebailar** [comment]
> Hey,
> 
> really interesting case. Can you try to use docker first before we dive deeper into this issue.
> 
> Kind regards
> 
> Selçuk

With docker_build.sh it works !

**Comment by khskekec** [comment]
Strange - apktool officially only requires Java but it looks like that it takes at least aapt from $PATH.

The mentioned xml attribute exists since android 12. Is it possible that your Android sdk does not include this api level? If you are using Android studio it should be easy to check.

Kind regards
Selçuk

**Comment by osodebailar** [comment]
> 

On the linux machine where i build the patched apk is no android studio or something else present

**Comment by khskekec** [comment]
Hmm, now nothing make any sense. Docker also only relies on Java image and installs git in addition. Nothing more?! Unclean env is also not possible because build.sh will clean up everything before it runs. To be honest I have no clue what's going on on your system 🤔😐.
