### ISSUE TITLE
Location issue

### ISSUE THREAD

**Issue by vanzaam** [DiaKEM/dexcom-g7-apk-patcher#39]
How can we resolve it? When we login from another country.
![log error](https://user-images.githubusercontent.com/5670673/228878295-cf0aa268-ad62-4088-90c4-dee91e797706.jpg)

**Comment by mxsrm** [comment]
VPN for login?

**Comment by vanzaam2** [comment]
> VPN for login?

VPN, GPS Fake etc - doesn’t work

**Comment by khskekec** [comment]
What happens with the stock app. Is this really related to this patch?
