### ISSUE TITLE
Patch doesn't work with new version 1.5.1.4174

### ISSUE THREAD

**Issue by rICTx-T1D** [DiaKEM/dexcom-g7-apk-patcher#40]
Hi folk,

under https://apkpure.com/de/dexcom-g7/com.dexcom.g7 is a newer version published. The patcher don't official support this, but I make a try to check complatiblity.

Here the result, after version 1.5.1.4174 was deployed at Apr 26, 2023:

`----------------------
🐌 Dexcom G7 APK-Patcher
ℹ️  Latest supported Dexcom G7 version: 1.4.0.3906
☢️  ALL INFORMATION AND OFFERED RESOURCES ARE HIGHLY EXPERIMENTAL AND NOT TESTED. USE AT YOUR OWN RISK! 🧪
----------------------
  ⏳ Removing old resources
   ✅ DONE
----------------------
  ⏳ Disassamble apk
I: Using Apktool 2.7.0 on dexcom.stock.apk
I: Loading resource table...
I: Decoding AndroidManifest.xml with resources...
I: Loading resource table from file: /root/.local/share/apktool/framework/1.apk
I: Regular manifest package...
I: Decoding file-resources...
I: Decoding values */* XMLs...
I: Baksmaling classes.dex...
I: Baksmaling classes2.dex...
I: Baksmaling classes3.dex...
I: Baksmaling classes4.dex...
I: Baksmaling classes5.dex...
I: Copying assets and libs...
I: Copying unknown files...
I: Copying original files...
I: Copying META-INF/services directory
   ✅ DONE
----------------------
  ⏳ Apply android manifest service patch
error: patch failed: dexcom-src/AndroidManifest.xml:115
error: dexcom-src/AndroidManifest.xml: patch does not apply
error: patch failed: dexcom-src/smali/kz/᫑ᫍ.smali:2746
error: dexcom-src/smali/kz/᫑ᫍ.smali: patch does not apply
error: patch failed: dexcom-src/smali/kz/᫛᫏.smali:3
error: dexcom-src/smali/kz/᫛᫏.smali: patch does not apply
error: patch failed: dexcom-src/smali_classes4/kz/ࡱ᫛.smali:1
error: dexcom-src/smali_classes4/kz/ࡱ᫛.smali: patch does not apply
   ❌ FAILED
mv: cannot stat 'dexcom.patched.apk': No such file or directory
`

**Comment by mxsrm** [comment]
G7 started showing a warning that the app will stop working at the beginning of June if not updated.

**Comment by jaaufauvre** [comment]
> G7 started showing a warning that the app will stop working at the beginning of June if not updated.

![Screenshot_20230527-082712](https://github.com/DiaKEM/dexcom-g7-apk-patcher/assets/3964455/c5792f4a-a225-4d21-880c-5f95215b1e9b)

**Comment by khskekec** [comment]
Hey,

I will not provide a patch for v1.5 because it has significant issues and cannot be considered as stable. Actually I am working on patching for v1.6. Hopefully I will be able to provide it soon.

I will close this issue and will notify you on discord as soon as the new patch is available.

Kind regards

Selçuk
