### ISSUE TITLE
Patches are failing (no such file or directory): filename mismatch after apktool

### ISSUE THREAD

**Issue by OlegShirochenkov** [DiaKEM/dexcom-g7-apk-patcher#52]
Hello. I'm unable to apply patches to a Dexcom_G7_1.6.1.4537_Apkpure.apk due to file path difference in apktool.
```
  ⏳ Apply android manifest service patch
error: dexcom-src/smali/kz/??.smali: No such file or directory
error: dexcom-src/smali/kz/??.smali: No such file or directory
error: dexcom-src/smali_classes4/kz/??.smali: No such file or directory
```
I've replaced a non-printable symbols to a question marks.
This was expected to fail on a Windows, but is failing on Debian for me.
Same failure with 1.3.3 and 1.4.0.
How is it possible and where is the source of apktool 2.7.0 mismatch in a decoding?
apktool have generated the list of files with a question marks from obfuscated parts instead of non-printable characters as expected.
```
'?.1.smali'
'?.10.smali'
'?.11.smali'
'?.12.smali'
```
I wonder why I'm the only affected.
Please suggest.

**Comment by OlegShirochenkov** [comment]
It was required to set environment variables related to language.

**Comment by james28909** [comment]
> It was required to set environment variables related to language.

So you were able to compile the latest version?

**Comment by OlegShirochenkov** [comment]
> So you were able to compile the latest version?

I was able to compile 1.6.1.4537. I would not refer to it as to the latest one.

**Comment by james28909** [comment]
> > So you were able to compile the latest version?
> 
> I was able to compile 1.6.1.4537. I would not refer to it as to the latest one.

Not trying to be smart or negative, it's a legit question... But what is the benefit of compiling a version that is already released? I have the same version that you just compiled. What are the advantages of the official diakem latest apk and the one you compiled? Sorry if I sound obtuse, I really am not trying to be

**Comment by OlegShirochenkov** [comment]
@james28909 because I need more patches that are not provided in this project while they are provided in another similar project.
Also, I was unable to use this project to compile the package due to missing environment settings — there were no such requirements mentioned.

**Comment by khskekec** [comment]
Hey,

Let me know which extra steps were required and on which os so that I can extend the Readme.

Which project do you mean and which patches?

**Comment by OlegShirochenkov** [comment]
@khskekec I'm referring to a BYODA project — there were more necessary patches.
While there were no UTF-8 environment variables set on GNU/Linux (C environment set instead), unpacking of the Dexcom application package was corrupting obfuscated name classes by question marks instead of leaving them obfuscated.
Excuse me for not being specific enough because this was a while ago and since then I've switched from G7 to Anubis G6 transmitter + cheaper Dexcom One sensors due to observing several G7 sensors kind of defective (had to put back conductive sensor wire inside of insertion needle manually, otherwise wire would not be set under the skin left simply pressed between the skin and a sensor).

**Comment by ahmadptx1** [comment]
@OlegShirochenkov sorry to comment on this but how exactly you fix this issue, the current Linux us_en.UTF8 however, still generate [] unprintable characters.

**Comment by OlegShirochenkov** [comment]
@ahmadptx1 , unprintable characters is what you want: obfuscated class names. This doesn't cause a problem to recompile the project, even navigation is possible.
Question marks instead of unprintable characters is a problem - it won't be possible to recompile such project.
