### ISSUE TITLE
Do not send values during sensor error and warm up

### ISSUE THREAD

**Issue by khskekec** [DiaKEM/dexcom-g7-apk-patcher#8]
Actually the broadcast is triggered during sensor errors and also in the warm up phase. This might lead to wrong decisions in AAPS due to wrong values.

The broadcasting should only happen if the sensor is in a valid state.

**Comment by blaqone** [comment]
Found the same
![Uploading 13733C64-0EA3-494E-AC3E-D4C452EB7EF7.jpeg…]()

**Comment by khskekec** [comment]
Hi @mxsrm,

We started to debug this issue and hopefully willing come to a solution very fast.

I will keeping you informed.

**Comment by CaptainBalou** [comment]
Ideally the new sensor values get somehow matched to the old ones to don't get recalculation errors in AAPS because the reading minutes are different. Maybe during the first 8 readings the time could be moved to the real one. Don't know if AAPS can be tricked so easy. 😉

**Comment by khskekec** [comment]
So far there were no problematic values during sensor error or warmup phase for us especially. Therefore I will close this issue and would address it if it comes up again from someone else.

Kind regards

Selçuk
